### PR TITLE
Branch fix index error message

### LINKED ISSUE #254: invalid index error when adding or removing multiple contacts is not very specific
Image

### LINKED ISSUE #255: index-related error messages when adding contact with multiple groups is not very specific
Image

### PR DESCRIPTION
**Pull request by GuoGangQuan**
Close #255 
Close #254 

Change to following error message
image
image

### CODE REVIEW

**Review by tze088 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -45,17 +61,54 @@ public static Index parseIndex(String oneBasedIndex) throws ParseException {
      *
      * @throws ParseException if the specified index is invalid (not non-zero unsigned integer).
      */
-    public static Set<Index> parseIndexes(Collection<String> oneBasedIndexes) throws ParseException {
+    public static Set<Index> parseIndexesWithMessage(Collection<String> oneBasedIndexes, String errorMessage)
```
Comment (tze088) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]:
```suggestion
    private static Set<Index> parseIndexesWithMessage(Collection<String> oneBasedIndexes, String errorMessage)
```

**Review by tze088 — CHANGES_REQUESTED** [review]
Since the specified methods should not be used from outside this class, it's best that they should be set to private.

I believe this change will violate checkstyle, so some reordering might be needed.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (GuoGangQuan) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: applied
