### PR TITLE
Fix invaild person in group while reading from storage

### LINKED ISSUE #137: It's possible to manually edit the JSON file such that a group contains a person which is not in the global contacts list
### Possible solution:

If we ensure that the global contacts list is read first, check whether each person added to group is in the contacts list.

This is an issue because the app will not throw any errors on reading from the incorrect file, leading to operation errors.

### PR DESCRIPTION
**Pull request by GuoGangQuan**
This PR resolved #137 where it address following bugs:

Bug: It's possible to manually edit the JSON file such that a group contains a person which is not in the global contacts list
Solution: checkExistenceOfPersonsInGroup method which check base on equals methods in person. (I am using List.contains() and List.contains() uses the equals() method of the objects in the list which is equals methods in person)

Bug: It's possible to manually edit the JSON file such that a person contains a group which is not in the global contacts list
Solution: checkExistenceOfGroupsInPerson method which check base on isSameGroup method in Group class (which only check the GroupName).

Close #137

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 1]
```diff
@@ -66,9 +70,37 @@ public AddressBook toModelType() throws IllegalValueException {
...
+            checkExistenceOfGroupsInPerson(addressBook, person);
+        }
+
         return addressBook;
     }
 
+    private void checkExistenceOfPersonsInGroup(Group group, ObservableList<Person> globalPersonList)
+            throws IllegalValueException {
+        for (Person person : group.getPersons()) {
+            if (!globalPersonList.contains(person)) {
```
Comment (tze088) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: PersonList.contains(person) only checks equality by name - this could still cause unwanted behaviour! Should check using Person.equals() instead.

Comment (GuoGangQuan) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: it is actually using Person.equals(), because List.contains() uses the equals() method of the objects in the list which is equals methods in person

Comment (tze088) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: You're right - I missed that globalPersonList is an ObservableList

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 2]
```diff
@@ -66,9 +70,37 @@ public AddressBook toModelType() throws IllegalValueException {
...
+            }
+        }
+    }
+
+    private void checkExistenceOfGroupsInPerson(AddressBook addressBook, Person person)
+            throws IllegalValueException {
+        for (GroupName groupName : person.getGroups()) {
+            Group checkGroup = new Group(groupName);
+            if (!addressBook.getGroupList().stream()
+                    .anyMatch(existingGroup -> existingGroup.isSameGroup(checkGroup))) {
```
[the remark this answers is not in the document]
Comment (tze088) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java]: Yup, looks good apart from the indentation.
Could also use stream().noneMatch instead of !stream().anymatch, but that's just being pedantic.
