### PR TITLE
Branch reduce email complexity

### LINKED ISSUE #303: [PE-D][Tester B] Clearer formatting of NUS email constraints
The email constraint can be enhanced to highlight the need for digits after the `e`.

For example:
`Must follow the format eXXXXXXX@u.nus.edu, where X is a digit from 0 - 9 (e.g.e0123456@u.nus.edu)`
instead of the current one
`Must follow the format eXXXXXXX@u.nus.edu (e.g., e0123456@u.nus.edu)`

This has been highlighted in the error message that appears upon an invalid email as well:

Emails should follow these constraints:
- is case-sensitive 
- Must start with 'e'
- Follow by 7 digit
- Must end with '@u.nus.edu'
example: e1234567@u.nus.edu

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #337: [PE-D][Tester C] Email is restricted to NUS email format only (too narrow for projects)
Email validation only allows `eXXXXXXX@u.nus.edu`, limiting usage to strictly NUS addresses

**Steps to reproduce:**

1. Run `add-contact n/John Doe p/98765432 e/johnd@example.com`.
    

**Expected:**

- Accepts common non-NUS emails (for projects using non-NUS emails).

**Actual:**

- Rejected unless the email matches `eXXXXXXX@u.nus.edu`.

Image
    

**Impact:**

- Restricts the app to NUS email; less useful for project groups that use non-NUS emails.
- Restricts the app to NUS-only participants; less useful for typical project groups with external stakeholders, tutors, or mentors who may not have NUS accounts.

**Suggested Improvements:**

- Broaden email validation to accept any standard email address format (using a general regex).
- Optionally, allow users to configure or toggle the NUS-only restriction (e.g., via a settings command or application flag).

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #354: [PE-D][Tester C] Overzealous input validation for email — requires full NUS address instead of accepting just student ID
The email validation is overly strict — users must type the entire NUS email address (e.g., `e1234567@u.nus.edu`) even though all NUS student emails share the same standard domain, and only NUS emails are allowed.
This makes data entry unnecessarily tedious for users who could otherwise enter just the student ID.

**Steps to reproduce:**

**Run:**

`add-contact n/John p/98765432 e/e1234567`

The command is rejected because the full domain `@u.nus.edu` is missing.

**Expected:**
- The app should accept the student ID (`e1234567`) and automatically append the domain `@u.nus.edu`.
- Validation should be flexible enough to infer valid NUS email formats based on the e-prefix.

**Actual:**
- The app rejects the command unless the full email `e1234567@u.nus.edu` is provided.

Image

**Impact**:

- Reduces typing efficiency and slows down workflow for users entering multiple contacts.
- Adds unnecessary strictness without improving data accuracy, since all NUS emails follow the same pattern.

**Suggested Improvements:**

- Relax email validation to allow users to input only the student ID (`e1234567`), automatically appending @u.nus.edu during processing.
- Alternatively, implement auto-complete to suggest the inferred full email for confirmation.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #355: [PE-D][Tester A] Contact email redundancy
Since the format of the email is fixed, the user should simply input the 7 digits to prevent inputting so many characters

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by GuoGangQuan**
Email constraint is change to the following:
Emails should follow these constraints:
your nus ID start with 'e' followed by 7 digits, and is case sensitive
example: e1234567@u.nus.edu (domain '@u.nus.edu' will be added automatically)

Close #303 
Close #355
Close #354
Close #337

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Email.java [hunk 1]
```diff
@@ -10,16 +10,12 @@
 public class Email {
 
     public static final String MESSAGE_CONSTRAINTS = "Emails should follow these constraints:\n"
-            + "- is case-sensitive \n"
-            + "- Must start with 'e'\n"
-            + "- Follow by 7 digit\n"
-            + "- Must end with '@u.nus.edu'\n"
-            + "example: e1234567@u.nus.edu";
+            + "your nus ID start with 'e' followed by 7 digits, and is case sensitive\n"
```
Comment (tze088) [inline src/main/java/seedu/address/model/person/Email.java]:
```suggestion
            + "An NUS ID starting with 'e' followed by 7 digits (case sensitive)\n"
```

File: src/main/java/seedu/address/model/person/Email.java [hunk 2]
```diff
@@ -10,16 +10,12 @@
...
+            + "example: e1234567@u.nus.edu (domain '@u.nus.edu' will be added automatically)";
```
Comment (tze088) [inline src/main/java/seedu/address/model/person/Email.java]:
```suggestion
            + "example: e1234567 (domain '@u.nus.edu' will be added automatically)";
```

**Review by tze088 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/person/Email.java (hunk 2 above)
Comment (GuoGangQuan) [reply src/main/java/seedu/address/model/person/Email.java]: Fix

File: src/main/java/seedu/address/model/person/Email.java (hunk 1 above)
Comment (GuoGangQuan) [reply src/main/java/seedu/address/model/person/Email.java]: Fix
